---
title: "Applied Statistics in Education and Human Services I"
description: |
  This course provides a first introduction to quantitative data analysis in education and the social sciences.
site: distill::distill_website
---

## Course Information

- Course Title		: Applied Statistics in Education and Human Services I

- Course Number		: EDUC 641

- Instructor			: Dr. Cengiz Zopluoglu [(Click for pronunciation)](https://namedrop.io/cengizzopluoglu)

- E-mail				  : cengiz@uoregon.edu


This course provides a first introduction to quantitative data analysis in education and the social sciences. It is part of a three course sequence intended to provide a toolkit of statistical concepts, methods and their implementation to producers of applied research in education and other social sciences. The course is organized around the principle that research design depends in part on researchers’ substantive questions and their quantitative data available to answer these question. In this introductory course, we will focus on describing categorical and continuous data and quantifying the relationship between categorical and continuous data. Students will form a solid foundation for frequentist, inferential statistics (and some of critiques of this model). The course seeks to blend a conceptual, mathematical and applied understanding of basic statistical concepts. At the core of our pedagogical approach is the belief that students learn statistical analysis by doing statistical analysis. This course (or substitute) is a pre-requisite for EDUC 643.

By the end of this term, it is expected that students will be able to:

- Articulate the principles of responsible and ethical quantitative research in education and human services
- Describe, summarize and visualize quantitative data that are categorical and continuous
- Describe, summarize and visualize the relationships between quantitative data that are categorical and continuous
- Conduct a frequentist null-hypothesis significance test of the relationships between simple categorical and continuous data
- Describe strategies to improve the replicability and generalizability of quantitative research
- Use an open-source, object-oriented statistical programming language (in this case R) to conduct all such analyses



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```