---
title: "Principles of Quantitative Research "
subtitle: "EDUC 641: Week 1"
author: "Cengiz Zopluoglu"
#date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: ['default', 'uo', 'ki-fonts', 'my_custom.css', 'xaringanthemer.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: true

---


<style>

#infobox {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  border: 2px solid black;
  border-radius: 10px;
  background: #E6F6DC 5px center/3em no-repeat;
}

.left-column2 {
  width: 75%;
  height: 92%;
  float: left;
  padding-top: 1em;
}

.right-column2 {
  width: 20%;
  float: right;
  padding-top: 1em;
}

.remark-code {
  font-size: 18px;
}

.tiny .remark-code { /*Change made here*/
  font-size: 70% !important;
}

</style>

```{R, setup, include = F}
library(pacman)
p_load(here, tidyverse, ggplot2, xaringan, knitr, kableExtra, xaringanthemer)

i_am("slides/EDUC641_week1.Rmd")


red_pink <- "#e64173"
turquoise = "#20B2AA"
orange = "#FFA500"
red = "#fb6107"
blue = "#3b3b9a"
green = "#8bb174"
grey_light = "grey70"
grey_mid = "grey50"
grey_dark = "grey20"
purple = "#6A5ACD"
slate = "#314f4f"

extra_css <- list(
  ".red"   = list(color = "red"),
  ".blue"  = list(color = "blue"),
  ".red-pink" = list(color= "red_pink"),
  ".grey-light" = list(color= "grey_light"),
  ".purple" = list(color = "purple"),
  ".large" = list("font-size" = "120%"),
  ".small" = list("font-size" = "90%"),
  ".tiny" = list("font-size" = "70%"),
  ".tiny2" = list("font-size" = "50%"))

write_extra_css(css = extra_css, outfile = "my_custom.css")

# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 6.75,
  fig.width = 10.5,
  warning = F,
  message = F
)
opts_chunk$set(dev = "svg")
options(device = function(file, width, height) {
  svg(tempfile(), width = width, height = height)
})
options(knitr.table.format = "html")

```

# What is (Quantitative) Scientific Research? 

* A systematic, evidence-based process to answer questions

--

* Seeks to build cumulative, testable, and reliable knowledge

--

* Features of (Quantitative) Scientific Research: 

  * empirical
  * systematic
  * defined sample and population
  * contextualized
  * reliable/valid
  * disprovable
  * peer-reviewed

---

## Features of (Quantitative) Scientific Research

--

* **Empirical**: Scientific research is built on observable evidence, not just opinion or belief

  * ❌ Non-scientific: “Eugene students are happier because they live in a green city.”

      Based on assumption and belief; no systematic observation.

  * ✅ Scientific: “Survey data from 300 Eugene students show those who spend 5+ hours per week in local parks score higher on validated well-being scales than those who don’t.”

--

* **Systematic**: Scientific research follows structured methods (research design, data collection, analysis)

  * ❌ Non-scientific: “I’ll just ask a few students I know and see what they think about math tutoring.”

  * ✅ Scientific: “A randomized controlled study assigns 100 UO students to tutoring and 100 to no-tutoring to test effects on final exam scores.”

---

* **Defined sample and population**: Scientific research clearly state who is studied and who results can generalize to

  * ❌ Non-scientific: "Students  were surveyed about online learning"

	      which students? from where? how many?

  * ✅ Scientific: “A sample of 250 undergraduates in the College of Education was surveyed, about online learning”

--

* **Contextualized**: Scientific research acknowledges the social, cultural, historical, and institutional conditions shaping both the problem and its possible answers.

  * ❌ Non-scientific: “All U.S. college towns have the same student housing challenges."
	
	     overgeneralizes, ignore differences in history, zoning, and community culture.

  * ✅ Scientific: “In Eugene, student housing shortages are influenced by the city’s zoning policies, rental market conditions, and the University of Oregon’s enrollment growth — factors that may differ substantially from other college towns.”

---

* **Reliable and valid**: Scientific research use measures that are consistent (reliable) and capture what they intend to measure (valid)

	* ❌ Non-scientific: “I measured stress in UO students by asking if they like pizza.”

	* ✅ Scientific: “Stress was measured using a validated 10-item Perceived Stress Scale administered to 150 UO students, with high reliability (α = .86).”

--

* **Disprovable**: Scientific research questions/hypothesis should be framed so that evidence (data) could falsify a claim

  * “Using mindfulness always improves learning.”
  
      This is vague, unfalsifiable, and hard to test because “improves learning” isn’t defined or measured consistently.

  * “Students in 5th grade at Edison Elementary in Eugene who receive 10 minutes of guided mindfulness before math class will score higher on the end-of-term math test than students who do not.”
  
      This is testable because evidence could falsify it: if test scores don’t differ (or the control group scores higher), the hypothesis is rejected.

---

* **Peer-Reviewed**: Findings must be evaluated by independent experts before becoming part of the scientific record.

	* ❌ Non-scientific: “I’ll just post my study on my blog; that’s enough to prove it’s true.”

	* ✅ Scientific: “UO Prevention Science Institute researchers publish in a peer-reviewed journal, where experts critique methodology, analysis, and conclusions before acceptance.”

---

These features of (quantitative) research should guide how to formulate **research questions**.

--

According to Light, Singer, & Willett (1990), good research questions:

--

* Identify the target population (who are you studying?)

--

* Determine level of aggregation (individual, classroom, school, district) 

--

* Identify the outcome variables and determine key predictors (what are you measuring, what predictors may explain variation in the outcome?)

--

* Determine the measures to use (are tools reliable, valid, and feasible?)

--

* Determine the sample size (how many cases needed to detect a relationship?)

-- 

* Determine the type of study most appropriate (descriptive, relational, or experimental)






## Research design and statistics

* This sequence focuses on statistics, but **research design** is AS (MORE?) important

--

* It can be tempting to use statistical techniques to fix poor research design

  * "You can't fix by analysis what you bungled by design" -Light, Singer & Willett. (1990). 
--

* Make sure you master content from EDUC 612, particularly concepts of: 

  * measurement, internal and external validity
 
--

* Strongly encourage you to consider courses in advanced research design (EDUC 646, EDLD 650, EDLD 679) after completing the quantitative EDUC sequence
